# .tarvis.yml
language: node_js # 指定语言环境
node_js:
  - stable # 指定 NodeJS 版本
sudo: required # 是否需要 sudo 权限

branches: # 指定要构建的分支
  only: # only 表示只构建以下分支
  - hexo

# Start: Build Lifecycle
install: # 在安装项目环境阶段需要运行的命令，一条一行，类似的还有 before_install
  - source travis_env_init.sh # 执行指定的 shell 脚本来做初始化

  # 设置git提交名，邮箱；替换真实token到_config.yml文件
before_script:

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

deploy:
  - sed -i'' "s~git@github.com:~https://s~git@github.com:~https://${GIT_REPO_TOKEN}@github.com/~" _config.yml
  - hexo deploy > /dev/null # 通过 hexo 的 deploy 命令部署博客

notifications:
  email:
    - 491071291@qq.com
  on_success: change
  on_failure: always