# .tarvis.yml
language: node_js # 指定语言环境
node_js:
  - stable # 指定 NodeJS 版本
sudo: required # 是否需要 sudo 权限

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

after_success:
  - hexo deploy

notifications: # 设置通知项
  email: true